"""check by hands

Revision ID: 828ab3bd1f9d
Revises: eb635fe07eee
Create Date: 2026-05-11 14:34:59.969249+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828ab3bd1f9d'
down_revision: Union[str, None] = 'eb635fe07eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('full_txt', sa.String(length=32768), nullable=True))
    op.add_column('resumes', sa.Column('file_path_pdf', sa.String(length=512), nullable=False))
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('resumes', 'file_path_pdf')
    op.drop_column('resumes', 'full_txt')
    # ### end Alembic commands ###
