"""fix unique vacancy_responses_user_id

Revision ID: a30e0c14b104
Revises: e7b20109892f
Create Date: 2026-05-12 10:16:08.781504+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30e0c14b104'
down_revision: Union[str, None] = 'e7b20109892f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_responses_user_id'), table_name='vacancy_responses')
    op.create_index(op.f('ix_vacancy_responses_user_id'), 'vacancy_responses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_responses_user_id'), table_name='vacancy_responses')
    op.create_index(op.f('ix_vacancy_responses_user_id'), 'vacancy_responses', ['user_id'], unique=True)
    # ### end Alembic commands ###
