"""init

Revision ID: eb635fe07eee
Revises: 
Create Date: 2026-05-10 18:11:12.826040+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb635fe07eee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_action_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_logs'))
    )
    op.create_index(op.f('ix_action_logs_action'), 'action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_action_logs_created_at'), 'action_logs', ['created_at'], unique=False)
    op.create_index('ix_action_logs_entity', 'action_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_action_logs_user_created', 'action_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('cover_letter_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cover_letter_templates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cover_letter_templates'))
    )
    op.create_index(op.f('ix_cover_letter_templates_user_id'), 'cover_letter_templates', ['user_id'], unique=False)
    op.create_table('identity_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('candidate_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('policy', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_identity_checks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_checks'))
    )
    op.create_index(op.f('ix_identity_checks_status'), 'identity_checks', ['status'], unique=False)
    op.create_index(op.f('ix_identity_checks_user_id'), 'identity_checks', ['user_id'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index('ix_job_runs_user_worker_started', 'job_runs', ['user_id', 'worker_name', 'started_at'], unique=False)
    op.create_index(op.f('ix_job_runs_worker_name'), 'job_runs', ['worker_name'], unique=False)
    op.create_index('ix_job_runs_worker_started', 'job_runs', ['worker_name', 'started_at'], unique=False)
    op.create_table('platform_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('encrypted_creds', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_session', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_platform_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_credentials')),
    sa.UniqueConstraint('user_id', 'platform', name='uq_platform_credentials_user_platform')
    )
    op.create_index(op.f('ix_platform_credentials_user_id'), 'platform_credentials', ['user_id'], unique=False)
    op.create_table('resume_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resume_url', sa.String(length=512), nullable=True),
    sa.Column('resume_id', sa.String(length=64), nullable=True),
    sa.Column('hh_session_file', sa.String(length=512), nullable=False),
    sa.Column('hh_phone', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resume_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_jobs'))
    )
    op.create_index(op.f('ix_resume_jobs_status'), 'resume_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_resume_jobs_user_id'), 'resume_jobs', ['user_id'], unique=False)
    op.create_index('uq_resume_jobs_user_id_active', 'resume_jobs', ['user_id'], unique=True, postgresql_where=sa.text("status in ('queued','running')"))
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('parsed_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resumes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index(op.f('ix_resumes_content_hash'), 'resumes', ['content_hash'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('external_payment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('user_id', name=op.f('uq_subscriptions_user_id'))
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('auto_apply_running', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('salary', sa.String(length=128), nullable=True),
    sa.Column('work_formats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('about_me', sa.String(length=1023), nullable=True),
    sa.Column('stop_companies', sa.Text(), nullable=True),
    sa.Column('stop_words', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('timezone_name', sa.String(length=64), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('notif_email', sa.Boolean(), nullable=False),
    sa.Column('notif_push', sa.Boolean(), nullable=False),
    sa.Column('notif_messages', sa.Boolean(), nullable=False),
    sa.Column('notif_weekly', sa.Boolean(), nullable=False),
    sa.Column('notif_telegram', sa.Boolean(), nullable=False),
    sa.Column('ai_cover_letter_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_link_token', sa.String(length=64), nullable=True),
    sa.Column('pending_platform_otps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_preferences'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_content_hash'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index('uq_resume_jobs_user_id_active', table_name='resume_jobs', postgresql_where=sa.text("status in ('queued','running')"))
    op.drop_index(op.f('ix_resume_jobs_user_id'), table_name='resume_jobs')
    op.drop_index(op.f('ix_resume_jobs_status'), table_name='resume_jobs')
    op.drop_table('resume_jobs')
    op.drop_index(op.f('ix_platform_credentials_user_id'), table_name='platform_credentials')
    op.drop_table('platform_credentials')
    op.drop_index('ix_job_runs_worker_started', table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_worker_name'), table_name='job_runs')
    op.drop_index('ix_job_runs_user_worker_started', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_identity_checks_user_id'), table_name='identity_checks')
    op.drop_index(op.f('ix_identity_checks_status'), table_name='identity_checks')
    op.drop_table('identity_checks')
    op.drop_index(op.f('ix_cover_letter_templates_user_id'), table_name='cover_letter_templates')
    op.drop_table('cover_letter_templates')
    op.drop_index('ix_action_logs_user_created', table_name='action_logs')
    op.drop_index('ix_action_logs_entity', table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_created_at'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_action'), table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
